name: login

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Builds and Starts
        run: |
            docker-compose up -d

      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner

      - name: Install Chrome
        run: |
          sudo apt-get install google-chrome-stable

      - name: Install seleniumbase
        run: pip install seleniumbase

      - name: Install chromedriver
        run: |
            seleniumbase install chromedriver

      - name: Run Tests
        run: |
            selenium-side-runner seleniumide-tests/registration.side
