name: side_run_test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  name: Builds and Starts
  run: |
      docker-compose up -d


jobs:

  registration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner

      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable

      - name: Install seleniumbase
        run: pip install seleniumbase

      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver

      - name: Run Tests
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/registration.side

  login:
    runs-on: ubuntu-latest
    needs: registration
    steps:
      - uses: actions/checkout@v2

      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner

      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable

      - name: Install seleniumbase
        run: pip install seleniumbase

      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver

      - name: Run Tests
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/login.side

  post:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - uses: actions/checkout@v2

      - name: install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Selenium Side Runner
        run: |
          npm install -g selenium-side-runner

      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable

      - name: Install seleniumbase
        run: pip install seleniumbase

      - name: Install chromedriver
        run: |
          seleniumbase install chromedriver

      - name: Run Tests
        run: |
          selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumide-tests/post.side

