name: Webdiver test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f selenium-tests/requirements_wd.txt ]; then pip install -r selenium-tests/requirements_wd.txt; fi

    - name: install Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'

   - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable

    - name: Install seleniumbase
      run: pip install seleniumbase

    - name: Install chromedriver
      run: |
        sudo apt-get -yqq install chromium-chromedriver
#       seleniumbase install chromedriver

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest selenium-tests/webdriv.py
